
<!DOCTYPE html>
<html>
<head>
    <title>PHP and HTML Test</title>
</head>
<body>
    <h1>Testing PHP within an HTML Page</h1>
    <?php
    echo "<p>This paragraph is generated by PHP.</p>";

    // Dynamic list generation using PHP
    echo "<ul>";
    for ($i = 1; $i <= 5; $i++) {
        echo "<li>Item " . $i . "</li>";
    }
    echo "</ul>";
    ?>
</body>
</html>
